version: '2'
services:
    blogger-app:
        image: blogger
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://blogger-mysql:3306/blogger?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=blogger-elasticsearch:9300
        ports:
            - 8080:8080
    blogger-mysql:
        extends:
            file: mysql.yml
            service: blogger-mysql
    blogger-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: blogger-elasticsearch
